<!-- /**
 * Aprilo Software.
 *
 * @category Aprilo Software Private Limited
 * @package aprilo_Cashback
 * @author Aprilo
 * @copyright Copyright (c) Aprilo Software Private Limited (https://Aprilo.com)
 * @license https://store.Aprilo.com/license.html
 */ -->
<?php
$totalCashback = $block->getTotalCashbackAmount();
if ($totalCashback > 0) :
?>
    <div class="cashback-info">
        <!-- <h3>Total Cashback</h3> -->
        <p>You will get a cashback of <?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($totalCashback, true, false); ?> for the products in your cart.</p>
    </div>
<?php endif; ?>
