<!-- /**
 * Aprilo Software.
 *
 * @category Aprilo Software Private Limited
 * @package aprilo_Cashback
 * @author Aprilo
 * @copyright Copyright (c) Aprilo Software Private Limited (https://Aprilo.com)
 * @license https://store.Aprilo.com/license.html
 */ -->
<?php 
if($block->getProductTypeId() == 'mpgiftcard'){ ?>
<style>
    .cart.items.table .cart-item .product-item-details .field.qty{
        display:none;
    }
</style>
<?php } ?>
<?php
if ($block->getCashbackAmounts()):
?>
    <div class="cashback-info">
       <span class="cashback-message" style="background: #fdde01;padding: 2px;border-radius: 8px;width: fit-content;">
            <?= $block->getCashbackAmounts() ?>
        </span> 
    </div>
<?php endif; ?>
<?php
/**
 * Shopping cart additional info
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<?php
$name = $block->getNameInLayout();
foreach ($block->getChildNames($name) as $childName) {
    // phpcs:ignore Magento2.Security.LanguageConstruct.DirectOutput
    echo $block->getChildBlock($childName)->setItem($block->getItem())->toHtml();
}
?>