<?php $_product = $block->getProduct(); ?>
<div class="social-media-icons">
    <span style="font-weight:600;font-size:17px;">SHARE:</span>
</div>


<?php $_product = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Registry::class)->registry('product');?>
<div class="product-share">
    <div class="share-links">
        <a href="https://api.whatsapp.com/send?text=<?=$_product->getProductUrl()?>" target="_blank" rel="nofollow" data-tooltip="whatsapp" data-placement="bottom" title="whatsapp" class="share-whatsapp" data-original-title="Facebook">Facebook</a>
        <a href="https://www.facebook.com/sharer.php?u=<?php echo $_product->getProductUrl();?>" target="_blank" rel="nofollow" data-tooltip="" data-placement="bottom" title="" class="share-facebook" data-original-title="Facebook">Facebook</a>
	    <a href="https://twitter.com/intent/tweet?text=<?php echo $_product->getName();?>&amp;url=<?php echo $_product->getProductUrl();?>" target="_blank" rel="nofollow" data-tooltip="" data-placement="bottom" title="" class="share-twitter" data-original-title="Twitter">Twitter</a>
	    <a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $_product->getProductUrl();?>&amp;title=<?php echo $_product->getName();?>" target="_blank" rel="nofollow" data-tooltip="" data-placement="bottom" title="" class="share-linkedin" data-original-title="LinkedIn">LinkedIn</a>
	    <a href="mailto:?subject=<?php echo $_product->getName();?>&amp;body=<?php echo $_product->getProductUrl();?>" target="_blank" rel="nofollow" data-tooltip="" data-placement="bottom" title="" class="share-email" data-original-title="Email">Email</a>
        <a href="javascript:void(0)" id ="copyLink" onclick="document.body.appendChild(document.createElement('input')).value=window.location.href;tempInput=document.body.lastChild;tempInput.select();document.execCommand('copy');document.body.removeChild(tempInput);this.setAttribute('title', 'URL copied!');setTimeout(function() {document.getElementById('copyLink').setAttribute('title', 'Click to copy URL');}, 2000);" rel="nofollow" data-tooltip="share copy url" data-placement="bottom" title="share" class="fa-share" data-original-title="copy" style="text-indent: 0em;line-height:30px;"><i class="fa fa-share-alt"></i></a>
    </div>
</div>