<!-- /**
 * Aprilo Software.
 *
 * @category Aprilo Software Private Limited
 * @package aprilo_Cashback
 * @author Aprilo
 * @copyright Copyright (c) Aprilo Software Private Limited (https://Aprilo.com)
 * @license https://store.Aprilo.com/license.html
 */ -->
<?php 
if ($block->isModuleEnabled() && $block->getCashbackAmount()): ?>
    <div class="cashback-message" style="background: #fdde01;padding: 5px;border-radius: 8px;width: fit-content;">
     <?= $block->getCashbackMessage() ?>
    </div>
<?php endif; ?>
